management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: ${JWT_SECRET:your-super-secret-key-that-is-at-least-32-bytes-long}
  issuer: slot-auth-service


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE
    org.springframework.web.servlet.function: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] [%X{userId}]  %-5level [%logger{0}] - %msg%n"
