management:
  tracing:
    enabled: true
    sampling:
      probability: 0.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

jwt:
  secret: ${JWT_SECRET:your-super-secret-key-that-is-at-least-32-bytes-long}
  issuer: slot-auth-service


logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.loadbalancer: INFO
    org.springframework.web.servlet.function: INFO
    io.github.resilience4j.circuitbreaker: DEBUG
    org.springframework.cloud.circuitbreaker: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}][%X{traceId}][%X{spanId}] [%X{userId}][%X{type}][%X{role}] [%-5level][%logger{0}] - %msg%n"
