spring:
  application:
    name: slot-api-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${SERVER_PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}

resilience4j:
  timelimiter:
    instances:
      auth-service:
        timeout-duration: 5s
        cancel-running-future: true
      bank-service:
        timeout-duration: 5s
        cancel-running-future: true
      floor-management-service:
        timeout-duration: 5s
        cancel-running-future: true
  circuitbreaker:
    instances:
      auth-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
      bank-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
      floor-management-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true